export interface DeliveryOrderModel {
    _id: string,
    date: Date,
    transactionDate: Date,
    orderNumber: string,
    referenceNumber: string,
    transactionType: string,
    orderSource: string,
    deliveryType: string,
    vehicleNumber: string,
    coustomer: string,
    customerType: string,
    salesPerson: string,
    salesOrder: string,
    purchaseOrder: string,
    shippingAddress: string,
    totalBuill: string,
    status: number,
    createAt: string,
    updateAt: string,
    deleteAt: string,
  }